### PR TITLE
Feature/close post page on esc key press

### PR DESCRIPTION
**Pull request by mdecourcy**

### CODE REVIEW

**Comment by mdecourcy** [comment]
Hmm.. Noticing that this breaks after some closes. Going to look in to further.

**Comment by sheodox** [comment]
Hey, I've got a few suggestions!

First, I'd recommend attaching a listener to [`<svelte:document>`](https://svelte.dev/docs/special-elements#svelte-document), that way svelte will clean up handlers when the component unmounts. 

Secondly I'd recommend checking `event.target` isn't an input or a textarea, otherwise if you press escape while writing a comment and it'd close the post on you.

**Comment by mdecourcy** [comment]
Thanks for the tips! I added a check for input/textarea, and tried attaching the listener like `svelte:document on:keydown={handleEscapeKey} />`

But, that seemed to result in more unstable behavior. Current commit still seems to crash. Going to continue digging in to this

**Comment by sheodox** [comment]
I just added the ability to close posts with Escape, along with support for a few extra hotkeys, so I'm going to close this PR. Thanks!

**Pull request closed without merging**
